using Iced.Intel;

namespace InlineAssembly;

// TODO Move into output generated by InlineAssembly.Generator to avoid warnings from having two
// different copies of this class
public static class Generator
{
    public static Assembler AddVariables(this Assembler assembler, params VariableData[] _)
    {
        // Variables are handled by the source generator, this function is only here to ensure compilation is possible
        return assembler;
    }
}
